# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when a release is created
on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'The name to use for the repository'     
        required: true
        default: 'notebook'

name: Deploy infrastructure on AWS

jobs:
  deploy-infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Create images repository with CloudFormation
      id: ecr-repository-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ga-stack01-${{ github.event.inputs.repository_name }}
        template: .aws/cloudformation-templates/ecr_repository.cf.yaml
        role-arn: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/ga-cloudformation-stack-role
        no-fail-on-empty-changeset: "1"
          
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ga-stack01-${{ github.event.inputs.repository_name }}-repository
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Retrieve default VPC ID and public subnets
      id: vpc
      run: |
        VPC_ID=`aws ec2 describe-vpcs --filters "Name=isDefault, Values=true" --query 'Vpcs[].VpcId' --output text`
        echo "::set-output name=vpc-id::$VPC_ID"
        SUBNET_1=`aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" "Name=default-for-az,Values=true" --query 'Subnets[0].SubnetId' --output text`
        echo "::set-output name=subnet-one::$SUBNET_1"
        SUBNET_2=`aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" "Name=default-for-az,Values=true" --query 'Subnets[1].SubnetId' --output text`
        echo "::set-output name=subnet-two::$SUBNET_2"

    - name: Create cluster in AWS with CloudFormation
      id: ecs-cluster-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ga-stack02-${{ github.event.inputs.repository_name }}
        template: .aws/cloudformation-templates/ecs_cluster.cf.yaml
        role-arn: arn:aws:iam::${{ steps.creds.outputs.aws-account-id }}:role/ga-cloudformation-stack-role
        no-fail-on-empty-changeset: "1"
        capabilities: "CAPABILITY_NAMED_IAM"
        parameter-overrides: >-
          ImageName=${{ steps.build-image.outputs.image }},
          KeyName=github-actions-kp,
          VpcId=${{ steps.vpc.outputs.vpc-id }},
          PublicSubnetOne=${{ steps.vpc.outputs.subnet-one }},
          PublicSubnetTwo=${{ steps.vpc.outputs.subnet-two }}
